# Place holder for tests makefile
.PHONY: all instrument_tests language_tests

all: instrument_tests language_tests

instrument_tests:
	./test_driver instrument_tests

language_tests:
	./test_driver language_tests